"""Hand-curated starter dataset so the game runs without a TMDb key.

Credits are intentionally partial (principal cast, director, music) and limited
to well-documented films. Run `fetch_tmdb.py` for the full dataset.

Row format: (title, year, lang, directors, music, cast)
"""

FILMS = [
    # --- Telugu ---
    ("Baahubali: The Beginning", 2015, "te", ["S. S. Rajamouli"], ["M. M. Keeravani"],
     ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia", "Ramya Krishnan", "Sathyaraj", "Nassar"]),
    ("Baahubali 2: The Conclusion", 2017, "te", ["S. S. Rajamouli"], ["M. M. Keeravani"],
     ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia", "Ramya Krishnan", "Sathyaraj", "Nassar"]),
    ("RRR", 2022, "te", ["S. S. Rajamouli"], ["M. M. Keeravani"],
     ["N. T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn", "Alia Bhatt", "Olivia Morris", "Shriya Saran", "Samuthirakani"]),
    ("Eega", 2012, "te", ["S. S. Rajamouli"], ["M. M. Keeravani"],
     ["Nani", "Samantha Ruth Prabhu", "Sudeep"]),
    ("Magadheera", 2009, "te", ["S. S. Rajamouli"], ["M. M. Keeravani"],
     ["Ram Charan", "Kajal Aggarwal", "Dev Gill", "Srihari"]),
    ("Pushpa: The Rise", 2021, "te", ["Sukumar"], ["Devi Sri Prasad"],
     ["Allu Arjun", "Rashmika Mandanna", "Fahadh Faasil", "Sunil", "Jagadeesh Prathap Bandari"]),
    ("Pushpa 2: The Rule", 2024, "te", ["Sukumar"], ["Devi Sri Prasad"],
     ["Allu Arjun", "Rashmika Mandanna", "Fahadh Faasil", "Jagapathi Babu"]),
    ("Rangasthalam", 2018, "te", ["Sukumar"], ["Devi Sri Prasad"],
     ["Ram Charan", "Samantha Ruth Prabhu", "Aadhi Pinisetty", "Jagapathi Babu", "Prakash Raj", "Anasuya Bharadwaj"]),
    ("Arya", 2004, "te", ["Sukumar"], ["Devi Sri Prasad"],
     ["Allu Arjun", "Anuradha Mehta", "Siva Balaji"]),
    ("Ala Vaikunthapurramuloo", 2020, "te", ["Trivikram Srinivas"], ["Thaman S"],
     ["Allu Arjun", "Pooja Hegde", "Tabu", "Jayaram", "Samuthirakani", "Murali Sharma"]),
    ("Arjun Reddy", 2017, "te", ["Sandeep Reddy Vanga"], ["Radhan"],
     ["Vijay Deverakonda", "Shalini Pandey", "Rahul Ramakrishna"]),
    ("Geetha Govindam", 2018, "te", ["Parasuram"], ["Gopi Sundar"],
     ["Vijay Deverakonda", "Rashmika Mandanna"]),
    ("Mahanati", 2018, "te", ["Nag Ashwin"], ["Mickey J. Meyer"],
     ["Keerthy Suresh", "Dulquer Salmaan", "Samantha Ruth Prabhu", "Vijay Deverakonda"]),
    ("Kalki 2898 AD", 2024, "te", ["Nag Ashwin"], ["Santhosh Narayanan"],
     ["Prabhas", "Amitabh Bachchan", "Kamal Haasan", "Deepika Padukone", "Disha Patani"]),
    ("Salaar: Part 1 – Ceasefire", 2023, "te", ["Prashanth Neel"], ["Ravi Basrur"],
     ["Prabhas", "Prithviraj Sukumaran", "Shruti Haasan", "Jagapathi Babu", "Sriya Reddy"]),
    ("Sita Ramam", 2022, "te", ["Hanu Raghavapudi"], ["Vishal Chandrashekhar"],
     ["Dulquer Salmaan", "Mrunal Thakur", "Rashmika Mandanna", "Sumanth"]),
    ("Jersey", 2019, "te", ["Gowtam Tinnanuri"], ["Anirudh Ravichander"],
     ["Nani", "Shraddha Srinath"]),
    ("Okkadu", 2003, "te", ["Gunasekhar"], ["Mani Sharma"],
     ["Mahesh Babu", "Bhumika Chawla", "Prakash Raj"]),
    ("Pokiri", 2006, "te", ["Puri Jagannadh"], ["Mani Sharma"],
     ["Mahesh Babu", "Ileana D'Cruz", "Prakash Raj", "Nassar", "Ashish Vidyarthi"]),

    # --- Tamil ---
    ("Vikram", 2022, "ta", ["Lokesh Kanagaraj"], ["Anirudh Ravichander"],
     ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Suriya", "Kalidas Jayaram", "Narain"]),
    ("Master", 2021, "ta", ["Lokesh Kanagaraj"], ["Anirudh Ravichander"],
     ["Vijay", "Vijay Sethupathi", "Malavika Mohanan", "Arjun Das", "Andrea Jeremiah"]),
    ("Kaithi", 2019, "ta", ["Lokesh Kanagaraj"], ["Sam C. S."],
     ["Karthi", "Narain", "Arjun Das", "George Maryan"]),
    ("Leo", 2023, "ta", ["Lokesh Kanagaraj"], ["Anirudh Ravichander"],
     ["Vijay", "Trisha Krishnan", "Sanjay Dutt", "Arjun Sarja", "Gautham Vasudev Menon", "Mysskin", "Priya Anand"]),
    ("Super Deluxe", 2019, "ta", ["Thiagarajan Kumararaja"], ["Yuvan Shankar Raja"],
     ["Vijay Sethupathi", "Fahadh Faasil", "Samantha Ruth Prabhu", "Ramya Krishnan", "Mysskin"]),
    ("96", 2018, "ta", ["C. Prem Kumar"], ["Govind Vasantha"],
     ["Vijay Sethupathi", "Trisha Krishnan"]),
    ("Vikram Vedha", 2017, "ta", ["Pushkar–Gayathri"], ["Sam C. S."],
     ["R. Madhavan", "Vijay Sethupathi", "Shraddha Srinath", "Varalaxmi Sarathkumar"]),
    ("Jailer", 2023, "ta", ["Nelson Dilipkumar"], ["Anirudh Ravichander"],
     ["Rajinikanth", "Mohanlal", "Shiva Rajkumar", "Jackie Shroff", "Ramya Krishnan", "Vinayakan", "Tamannaah Bhatia"]),
    ("Petta", 2019, "ta", ["Karthik Subbaraj"], ["Anirudh Ravichander"],
     ["Rajinikanth", "Vijay Sethupathi", "Nawazuddin Siddiqui", "Simran", "Trisha Krishnan", "Sasikumar"]),
    ("Doctor", 2021, "ta", ["Nelson Dilipkumar"], ["Anirudh Ravichander"],
     ["Sivakarthikeyan", "Priyanka Arul Mohan", "Vinay Rai", "Yogi Babu", "Redin Kingsley"]),
    ("3", 2012, "ta", ["Aishwarya Rajinikanth"], ["Anirudh Ravichander"],
     ["Dhanush", "Shruti Haasan", "Sivakarthikeyan"]),
    ("Amaran", 2024, "ta", ["Rajkumar Periasamy"], ["G. V. Prakash Kumar"],
     ["Sivakarthikeyan", "Sai Pallavi", "Bhuvan Arora", "Rahul Bose"]),
    ("Aadukalam", 2011, "ta", ["Vetrimaaran"], ["G. V. Prakash Kumar"],
     ["Dhanush", "Taapsee Pannu", "Kishore", "V. I. S. Jayapalan"]),
    ("Asuran", 2019, "ta", ["Vetrimaaran"], ["G. V. Prakash Kumar"],
     ["Dhanush", "Manju Warrier", "Ken Karunas", "Teejay Arunasalam", "Pasupathy"]),
    ("Visaranai", 2015, "ta", ["Vetrimaaran"], ["G. V. Prakash Kumar"],
     ["Dinesh", "Samuthirakani", "Aadukalam Murugadoss", "Kishore"]),
    ("Soorarai Pottru", 2020, "ta", ["Sudha Kongara"], ["G. V. Prakash Kumar"],
     ["Suriya", "Aparna Balamurali", "Paresh Rawal", "Urvashi"]),
    ("Jai Bhim", 2021, "ta", ["T. J. Gnanavel"], ["Sean Roldan"],
     ["Suriya", "Lijomol Jose", "Manikandan", "Prakash Raj", "Rajisha Vijayan"]),
    ("Ghajini", 2005, "ta", ["A. R. Murugadoss"], ["Harris Jayaraj"],
     ["Suriya", "Asin", "Nayanthara", "Pradeep Rawat"]),
    ("Mersal", 2017, "ta", ["Atlee"], ["A. R. Rahman"],
     ["Vijay", "Samantha Ruth Prabhu", "Kajal Aggarwal", "Nithya Menen", "S. J. Suryah"]),
    ("Theri", 2016, "ta", ["Atlee"], ["G. V. Prakash Kumar"],
     ["Vijay", "Samantha Ruth Prabhu", "Amy Jackson", "Prabhu"]),
    ("Ghilli", 2004, "ta", ["Dharani"], ["Vidyasagar"],
     ["Vijay", "Trisha Krishnan", "Prakash Raj"]),
    ("Alaipayuthey", 2000, "ta", ["Mani Ratnam"], ["A. R. Rahman"],
     ["R. Madhavan", "Shalini"]),
    ("Roja", 1992, "ta", ["Mani Ratnam"], ["A. R. Rahman"],
     ["Arvind Swamy", "Madhoo"]),
    ("Bombay", 1995, "ta", ["Mani Ratnam"], ["A. R. Rahman"],
     ["Arvind Swamy", "Manisha Koirala", "Nassar"]),
    ("Nayakan", 1987, "ta", ["Mani Ratnam"], ["Ilaiyaraaja"],
     ["Kamal Haasan", "Saranya Ponvannan", "Janagaraj"]),
    ("Ponniyin Selvan: I", 2022, "ta", ["Mani Ratnam"], ["A. R. Rahman"],
     ["Vikram", "Aishwarya Rai Bachchan", "Karthi", "Jayam Ravi", "Trisha Krishnan",
      "Aishwarya Lekshmi", "Sobhita Dhulipala", "Prakash Raj", "Sarathkumar", "Prabhu"]),
    ("Enthiran", 2010, "ta", ["S. Shankar"], ["A. R. Rahman"],
     ["Rajinikanth", "Aishwarya Rai Bachchan", "Danny Denzongpa"]),
    ("Sivaji: The Boss", 2007, "ta", ["S. Shankar"], ["A. R. Rahman"],
     ["Rajinikanth", "Shriya Saran", "Suman", "Vivek"]),
    ("Indian", 1996, "ta", ["S. Shankar"], ["A. R. Rahman"],
     ["Kamal Haasan", "Manisha Koirala", "Urmila Matondkar", "Sukanya", "Nedumudi Venu"]),
    ("Baashha", 1995, "ta", ["Suresh Krissna"], ["Deva"],
     ["Rajinikanth", "Nagma", "Raghuvaran"]),

    # --- Malayalam ---
    ("Kumbalangi Nights", 2019, "ml", ["Madhu C. Narayanan"], ["Sushin Shyam"],
     ["Soubin Shahir", "Shane Nigam", "Sreenath Bhasi", "Mathew Thomas", "Fahadh Faasil", "Anna Ben"]),
    ("Maheshinte Prathikaaram", 2016, "ml", ["Dileesh Pothan"], ["Bijibal"],
     ["Fahadh Faasil", "Aparna Balamurali", "Anusree", "Soubin Shahir", "Alencier Ley Lopez"]),
    ("Aavesham", 2024, "ml", ["Jithu Madhavan"], ["Sushin Shyam"],
     ["Fahadh Faasil", "Sajin Gopu", "Hipzster", "Mithun Jai Shankar", "Roshan Shanavas"]),
    ("Manjummel Boys", 2024, "ml", ["Chidambaram"], ["Sushin Shyam"],
     ["Soubin Shahir", "Sreenath Bhasi", "Balu Varghese", "Ganapathi"]),
    ("Bangalore Days", 2014, "ml", ["Anjali Menon"], ["Gopi Sundar"],
     ["Dulquer Salmaan", "Nivin Pauly", "Nazriya Nazim", "Fahadh Faasil", "Parvathy Thiruvothu"]),
    ("Premam", 2015, "ml", ["Alphonse Puthren"], ["Rajesh Murugesan"],
     ["Nivin Pauly", "Sai Pallavi", "Madonna Sebastian", "Anupama Parameswaran"]),
    ("Lucifer", 2019, "ml", ["Prithviraj Sukumaran"], ["Deepak Dev"],
     ["Mohanlal", "Prithviraj Sukumaran", "Vivek Oberoi", "Manju Warrier", "Tovino Thomas"]),
    ("Drishyam", 2013, "ml", ["Jeethu Joseph"], [],
     ["Mohanlal", "Meena", "Ansiba Hassan", "Esther Anil", "Asha Sharath", "Siddique"]),
    ("Manichitrathazhu", 1993, "ml", ["Fazil"], ["M. G. Radhakrishnan"],
     ["Mohanlal", "Shobana", "Suresh Gopi", "Nedumudi Venu"]),
    ("Minnal Murali", 2021, "ml", ["Basil Joseph"], [],
     ["Tovino Thomas", "Guru Somasundaram", "Femina George"]),

    # --- Kannada ---
    ("Kantara", 2022, "kn", ["Rishab Shetty"], ["B. Ajaneesh Loknath"],
     ["Rishab Shetty", "Sapthami Gowda", "Kishore", "Achyuth Kumar"]),
    ("K.G.F: Chapter 1", 2018, "kn", ["Prashanth Neel"], ["Ravi Basrur"],
     ["Yash", "Srinidhi Shetty", "Ramachandra Raju", "Anant Nag", "Achyuth Kumar"]),
    ("K.G.F: Chapter 2", 2022, "kn", ["Prashanth Neel"], ["Ravi Basrur"],
     ["Yash", "Srinidhi Shetty", "Sanjay Dutt", "Raveena Tandon", "Prakash Raj"]),
    ("Kirik Party", 2016, "kn", ["Rishab Shetty"], ["B. Ajaneesh Loknath"],
     ["Rakshit Shetty", "Rashmika Mandanna", "Samyuktha Hegde"]),
    ("777 Charlie", 2022, "kn", ["Kiranraj K"], ["Nobin Paul"],
     ["Rakshit Shetty", "Sangeetha Sringeri", "Raj B. Shetty", "Danish Sait"]),

    # --- Marathi ---
    ("Sairat", 2016, "mr", ["Nagraj Manjule"], ["Ajay–Atul"],
     ["Rinku Rajguru", "Akash Thosar"]),

    # --- Hindi ---
    ("Jhund", 2022, "hi", ["Nagraj Manjule"], ["Ajay–Atul"],
     ["Amitabh Bachchan", "Akash Thosar", "Rinku Rajguru"]),
    ("Gangubai Kathiawadi", 2022, "hi", ["Sanjay Leela Bhansali"], ["Sanjay Leela Bhansali"],
     ["Alia Bhatt", "Ajay Devgn", "Shantanu Maheshwari", "Vijay Raaz", "Seema Pahwa"]),
    ("Gully Boy", 2019, "hi", ["Zoya Akhtar"], [],
     ["Ranveer Singh", "Alia Bhatt", "Siddhant Chaturvedi", "Kalki Koechlin", "Vijay Raaz"]),
    ("Padmaavat", 2018, "hi", ["Sanjay Leela Bhansali"], ["Sanjay Leela Bhansali"],
     ["Deepika Padukone", "Ranveer Singh", "Shahid Kapoor", "Jim Sarbh", "Aditi Rao Hydari"]),
    ("Bajirao Mastani", 2015, "hi", ["Sanjay Leela Bhansali"], ["Sanjay Leela Bhansali"],
     ["Ranveer Singh", "Deepika Padukone", "Priyanka Chopra", "Tanvi Azmi"]),
    ("Devdas", 2002, "hi", ["Sanjay Leela Bhansali"], ["Ismail Darbar"],
     ["Shah Rukh Khan", "Aishwarya Rai Bachchan", "Madhuri Dixit", "Jackie Shroff", "Kirron Kher"]),
    ("Hum Dil De Chuke Sanam", 1999, "hi", ["Sanjay Leela Bhansali"], ["Ismail Darbar"],
     ["Salman Khan", "Aishwarya Rai Bachchan", "Ajay Devgn"]),
    ("Om Shanti Om", 2007, "hi", ["Farah Khan"], ["Vishal–Shekhar"],
     ["Shah Rukh Khan", "Deepika Padukone", "Arjun Rampal", "Shreyas Talpade", "Kirron Kher"]),
    ("Chennai Express", 2013, "hi", ["Rohit Shetty"], ["Vishal–Shekhar"],
     ["Shah Rukh Khan", "Deepika Padukone", "Sathyaraj", "Nikitin Dheer"]),
    ("Jawan", 2023, "hi", ["Atlee"], ["Anirudh Ravichander"],
     ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi", "Deepika Padukone", "Priyamani", "Sanya Malhotra"]),
    ("Pathaan", 2023, "hi", ["Siddharth Anand"], ["Vishal–Shekhar"],
     ["Shah Rukh Khan", "Deepika Padukone", "John Abraham", "Dimple Kapadia"]),
    ("Dilwale Dulhania Le Jayenge", 1995, "hi", ["Aditya Chopra"], ["Jatin–Lalit"],
     ["Shah Rukh Khan", "Kajol", "Amrish Puri", "Anupam Kher", "Farida Jalal"]),
    ("Kuch Kuch Hota Hai", 1998, "hi", ["Karan Johar"], ["Jatin–Lalit"],
     ["Shah Rukh Khan", "Kajol", "Rani Mukerji", "Salman Khan", "Anupam Kher"]),
    ("Kabhi Khushi Kabhie Gham...", 2001, "hi", ["Karan Johar"], [],
     ["Amitabh Bachchan", "Jaya Bachchan", "Shah Rukh Khan", "Kajol", "Hrithik Roshan", "Kareena Kapoor Khan"]),
    ("Dil Se..", 1998, "hi", ["Mani Ratnam"], ["A. R. Rahman"],
     ["Shah Rukh Khan", "Manisha Koirala", "Preity Zinta"]),
    ("Swades", 2004, "hi", ["Ashutosh Gowariker"], ["A. R. Rahman"],
     ["Shah Rukh Khan", "Gayatri Joshi", "Kishori Ballal"]),
    ("Chak De! India", 2007, "hi", ["Shimit Amin"], ["Salim–Sulaiman"],
     ["Shah Rukh Khan", "Vidya Malvade", "Sagarika Ghatge", "Shilpa Shukla"]),
    ("Lagaan", 2001, "hi", ["Ashutosh Gowariker"], ["A. R. Rahman"],
     ["Aamir Khan", "Gracy Singh", "Rachel Shelley"]),
    ("Jodhaa Akbar", 2008, "hi", ["Ashutosh Gowariker"], ["A. R. Rahman"],
     ["Hrithik Roshan", "Aishwarya Rai Bachchan", "Sonu Sood", "Kulbhushan Kharbanda"]),
    ("Rockstar", 2011, "hi", ["Imtiaz Ali"], ["A. R. Rahman"],
     ["Ranbir Kapoor", "Nargis Fakhri", "Shammi Kapoor"]),
    ("Raanjhanaa", 2013, "hi", ["Aanand L. Rai"], ["A. R. Rahman"],
     ["Dhanush", "Sonam Kapoor", "Abhay Deol", "Mohammed Zeeshan Ayyub", "Swara Bhasker"]),
    ("Ghajini", 2008, "hi", ["A. R. Murugadoss"], ["A. R. Rahman"],
     ["Aamir Khan", "Asin", "Jiah Khan", "Pradeep Rawat"]),
    ("3 Idiots", 2009, "hi", ["Rajkumar Hirani"], ["Shantanu Moitra"],
     ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Kareena Kapoor Khan", "Boman Irani", "Omi Vaidya"]),
    ("PK", 2014, "hi", ["Rajkumar Hirani"], ["Shantanu Moitra"],
     ["Aamir Khan", "Anushka Sharma", "Sushant Singh Rajput", "Sanjay Dutt", "Boman Irani", "Saurabh Shukla"]),
    ("Munna Bhai M.B.B.S.", 2003, "hi", ["Rajkumar Hirani"], ["Anu Malik"],
     ["Sanjay Dutt", "Arshad Warsi", "Gracy Singh", "Boman Irani", "Sunil Dutt"]),
    ("Dangal", 2016, "hi", ["Nitesh Tiwari"], ["Pritam"],
     ["Aamir Khan", "Sakshi Tanwar", "Fatima Sana Shaikh", "Sanya Malhotra", "Zaira Wasim"]),
    ("Taare Zameen Par", 2007, "hi", ["Aamir Khan"], ["Shankar–Ehsaan–Loy"],
     ["Aamir Khan", "Darsheel Safary", "Tisca Chopra", "Vipin Sharma"]),
    ("Dil Chahta Hai", 2001, "hi", ["Farhan Akhtar"], ["Shankar–Ehsaan–Loy"],
     ["Aamir Khan", "Saif Ali Khan", "Akshaye Khanna", "Preity Zinta", "Dimple Kapadia", "Sonali Kulkarni"]),
    ("Zindagi Na Milegi Dobara", 2011, "hi", ["Zoya Akhtar"], ["Shankar–Ehsaan–Loy"],
     ["Hrithik Roshan", "Farhan Akhtar", "Abhay Deol", "Katrina Kaif", "Kalki Koechlin"]),
    ("Raazi", 2018, "hi", ["Meghna Gulzar"], ["Shankar–Ehsaan–Loy"],
     ["Alia Bhatt", "Vicky Kaushal", "Rajit Kapur", "Jaideep Ahlawat", "Soni Razdan"]),
    ("Uri: The Surgical Strike", 2019, "hi", ["Aditya Dhar"], ["Shashwat Sachdev"],
     ["Vicky Kaushal", "Yami Gautam", "Paresh Rawal", "Kirti Kulhari", "Mohit Raina"]),
    ("Masaan", 2015, "hi", ["Neeraj Ghaywan"], ["Indian Ocean"],
     ["Richa Chadha", "Vicky Kaushal", "Shweta Tripathi", "Sanjay Mishra", "Pankaj Tripathi"]),
    ("Gangs of Wasseypur", 2012, "hi", ["Anurag Kashyap"], ["Sneha Khanwalkar"],
     ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Richa Chadha", "Huma Qureshi", "Pankaj Tripathi", "Tigmanshu Dhulia"]),
    ("Satya", 1998, "hi", ["Ram Gopal Varma"], ["Vishal Bhardwaj"],
     ["J. D. Chakravarthy", "Manoj Bajpayee", "Urmila Matondkar", "Saurabh Shukla"]),
    ("Stree", 2018, "hi", ["Amar Kaushik"], ["Sachin–Jigar"],
     ["Rajkummar Rao", "Shraddha Kapoor", "Pankaj Tripathi", "Aparshakti Khurana", "Abhishek Banerjee"]),
    ("Queen", 2014, "hi", ["Vikas Bahl"], ["Amit Trivedi"],
     ["Kangana Ranaut", "Rajkummar Rao", "Lisa Haydon"]),
    ("Andhadhun", 2018, "hi", ["Sriram Raghavan"], ["Amit Trivedi"],
     ["Ayushmann Khurrana", "Tabu", "Radhika Apte"]),
    ("Drishyam", 2015, "hi", ["Nishikant Kamat"], ["Vishal Bhardwaj"],
     ["Ajay Devgn", "Tabu", "Shriya Saran", "Ishita Dutta"]),
    ("Haider", 2014, "hi", ["Vishal Bhardwaj"], ["Vishal Bhardwaj"],
     ["Shahid Kapoor", "Tabu", "Shraddha Kapoor", "Kay Kay Menon", "Irrfan Khan"]),
    ("Maqbool", 2003, "hi", ["Vishal Bhardwaj"], ["Vishal Bhardwaj"],
     ["Irrfan Khan", "Tabu", "Pankaj Kapur", "Naseeruddin Shah", "Om Puri"]),
    ("Omkara", 2006, "hi", ["Vishal Bhardwaj"], ["Vishal Bhardwaj"],
     ["Ajay Devgn", "Saif Ali Khan", "Kareena Kapoor Khan", "Vivek Oberoi", "Konkona Sen Sharma",
      "Naseeruddin Shah", "Bipasha Basu"]),
    ("Kabir Singh", 2019, "hi", ["Sandeep Reddy Vanga"], [],
     ["Shahid Kapoor", "Kiara Advani", "Soham Majumdar", "Arjan Bajwa"]),
    ("Animal", 2023, "hi", ["Sandeep Reddy Vanga"], [],
     ["Ranbir Kapoor", "Anil Kapoor", "Bobby Deol", "Rashmika Mandanna", "Tripti Dimri"]),
    ("Vikram Vedha", 2022, "hi", ["Pushkar–Gayathri"], ["Sam C. S."],
     ["Hrithik Roshan", "Saif Ali Khan", "Radhika Apte", "Rohit Saraf"]),
    ("Tanhaji: The Unsung Warrior", 2020, "hi", ["Om Raut"], [],
     ["Ajay Devgn", "Kajol", "Saif Ali Khan", "Sharad Kelkar"]),
    ("Singham", 2011, "hi", ["Rohit Shetty"], ["Ajay–Atul"],
     ["Ajay Devgn", "Kajal Aggarwal", "Prakash Raj"]),
    ("Bajrangi Bhaijaan", 2015, "hi", ["Kabir Khan"], ["Pritam"],
     ["Salman Khan", "Kareena Kapoor Khan", "Nawazuddin Siddiqui", "Harshaali Malhotra"]),
    ("Sultan", 2016, "hi", ["Ali Abbas Zafar"], ["Vishal–Shekhar"],
     ["Salman Khan", "Anushka Sharma", "Randeep Hooda", "Amit Sadh"]),
    ("Wanted", 2009, "hi", ["Prabhu Deva"], ["Sajid–Wajid"],
     ["Salman Khan", "Ayesha Takia", "Prakash Raj"]),
    ("Bhool Bhulaiyaa", 2007, "hi", ["Priyadarshan"], ["Pritam"],
     ["Akshay Kumar", "Vidya Balan", "Shiney Ahuja", "Amisha Patel", "Paresh Rawal", "Rajpal Yadav"]),
    ("Hera Pheri", 2000, "hi", ["Priyadarshan"], ["Anu Malik"],
     ["Akshay Kumar", "Suniel Shetty", "Paresh Rawal", "Tabu", "Om Puri"]),
    ("Kahaani", 2012, "hi", ["Sujoy Ghosh"], ["Vishal–Shekhar"],
     ["Vidya Balan", "Parambrata Chatterjee", "Nawazuddin Siddiqui", "Indraneil Sengupta"]),
    ("The Lunchbox", 2013, "hi", ["Ritesh Batra"], [],
     ["Irrfan Khan", "Nimrat Kaur", "Nawazuddin Siddiqui"]),
    ("Piku", 2015, "hi", ["Shoojit Sircar"], ["Anupam Roy"],
     ["Deepika Padukone", "Amitabh Bachchan", "Irrfan Khan", "Moushumi Chatterjee"]),
    ("Sholay", 1975, "hi", ["Ramesh Sippy"], ["R. D. Burman"],
     ["Amitabh Bachchan", "Dharmendra", "Sanjeev Kumar", "Hema Malini", "Jaya Bachchan", "Amjad Khan"]),
    ("Deewaar", 1975, "hi", ["Yash Chopra"], ["R. D. Burman"],
     ["Amitabh Bachchan", "Shashi Kapoor", "Nirupa Roy", "Parveen Babi"]),
]
